### PR TITLE
New docs

### PR DESCRIPTION
**Pull request by maxbertinetti**
For this version I removed ALL from docs and restarted.
At some point we need to reintroduce favicon, cname etc.

For local development you need ruby on your system.

`bundle install`
Install the dependencies locally (I think if you have ruby you also must have bundler, but in case you don't see  https://bundler.io/)

`bundle exec jekyll serve`
Starts the local server in development mode (it recompiles changes without quitting the server) on http://localhost:4000

For reference Just the docs repo and docs: https://github.com/pmarsceill/just-the-docs

### CODE REVIEW

**Comment by mvysny** [comment]
Whoa I did not expect a PR that literally changes everything. Why there is a need to change everything?

1. Will this work with Github Pages?
2. Will the CNAME work?

**Comment by maxbertinetti** [comment]
Yes absolutely

**Comment by mvysny** [comment]
Damn, I just don't like Ruby .... nevermind ;)

Okay, so what are the follow-up steps? Should I pull this into the new-docs branch? What about all existing guides and the missing CNAME file?

**Comment by maxbertinetti** [comment]
No. Just see it locally and tell me what you think.

I have to push missing pages and files like CNAME etc.

**Comment by mvysny** [comment]
Hmm, bundle install succeeds but prints
```
Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841
```
is the theme or the toolchain perhaps deprecated?

**Comment by maxbertinetti** [comment]
I don’t remember this, but can be something arriving from a dependency.

If you can launch the server and see docs locally do not worry

**Comment by mvysny** [comment]
I've got the jekyll to run and I *absolutely love* the new site. The split to vok-14 and vok-8 is really great. To be honest I'm even thinking of dropping vok-8 since Vaadin 8 is not really supported anymore - we could then remove all Vaadin8-related starters which should simplify the page.

The code example snippets look great as well. The `quickstarters.html` page formatting is broken at the moment but definitely something we can fix (or replace by a bunch of links).

All in all, excellent work, I love the new site. If you have more time, would you like to port the missing bits over to the new site?

**Comment by maxbertinetti** [comment]
Hey Martin, yes, I absolutely want to finish the porting.

The quickstarters page was not finished, that’s why seems broken.

I also think vok 8 can be removed, so if you confirm I will remove and simplify the flow.

I think I have time to finish on the next week end.

Then after you have verified the work, you can merge to master.

Cheers

Max

**Comment by mvysny** [comment]
> I also think vok 8 can be removed, so if you confirm I will remove and simplify the flow.

Yes please, go ahead and remove the vok 8 documentation. I'll also remove the vok-8 modules and example projects: https://github.com/mvysny/vaadin-on-kotlin/issues/63

Thank you again for all of your amazing work :+1:

**Comment by maxbertinetti** [comment]
Please verify if there is problems then you can merge to master to see the new docs site online.

**Comment by mvysny** [comment]
Excellent, I've reviewed the docs and found no issues. However, you should definitely deserve a credit for your work - perhaps we could modify the footer to read `Copyright © 2017-2021 Martin Vysny and Massimiliano Bertinetti`, or alternatively something like `This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License` linking to https://creativecommons.org/licenses/by-sa/4.0/ ?

**Comment by maxbertinetti** [comment]
Thanks. You can make the change that you like by yourself now. I think the footer text is in the _config.yamlHappy of being of help.Il 06 apr 2021 14:12, Martin Vysny ***@***.***> ha scritto:

Excellent, I've reviewed the docs and found no issues. However, you should definitely deserve a credit for your work - perhaps we could modify the footer to read Copyright © 2017-2021 Martin Vysny and Massimiliano Bertinetti, or alternatively something like This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License linking to https://creativecommons.org/licenses/by-sa/4.0/ ?

**Pull request merged**
